Fixed normalisation error in convolution
Added options to astropy convolve_fft call to avoid the following error:

Exception: The kernel can't be normalized, because its sum is close to
zero. The sum of the given kernel is < 0.01